// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -destination=mocks_world_test.go -package=httpstorage -source=server.go
//

// Package httpstorage is a generated GoMock package.
package httpstorage

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemoteStorage is a mock of RemoteStorage interface.
type MockRemoteStorage struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteStorageMockRecorder
	isgomock struct{}
}

// MockRemoteStorageMockRecorder is the mock recorder for MockRemoteStorage.
type MockRemoteStorageMockRecorder struct {
	mock *MockRemoteStorage
}

// NewMockRemoteStorage creates a new mock instance.
func NewMockRemoteStorage(ctrl *gomock.Controller) *MockRemoteStorage {
	mock := &MockRemoteStorage{ctrl: ctrl}
	mock.recorder = &MockRemoteStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteStorage) EXPECT() *MockRemoteStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRemoteStorage) Get(ctx context.Context, request *GetRequest) (*GetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, request)
	ret0, _ := ret[0].(*GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRemoteStorageMockRecorder) Get(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRemoteStorage)(nil).Get), ctx, request)
}

// Put mocks base method.
func (m *MockRemoteStorage) Put(ctx context.Context, request *PutRequest) (*PutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, request)
	ret0, _ := ret[0].(*PutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockRemoteStorageMockRecorder) Put(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRemoteStorage)(nil).Put), ctx, request)
}
