// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -destination=mocks_world_test.go -package=cacheprog -source=handler.go
//

// Package cacheprog is a generated GoMock package.
package cacheprog

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRemoteStorage is a mock of RemoteStorage interface.
type MockRemoteStorage struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteStorageMockRecorder
	isgomock struct{}
}

// MockRemoteStorageMockRecorder is the mock recorder for MockRemoteStorage.
type MockRemoteStorageMockRecorder struct {
	mock *MockRemoteStorage
}

// NewMockRemoteStorage creates a new mock instance.
func NewMockRemoteStorage(ctrl *gomock.Controller) *MockRemoteStorage {
	mock := &MockRemoteStorage{ctrl: ctrl}
	mock.recorder = &MockRemoteStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteStorage) EXPECT() *MockRemoteStorageMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRemoteStorage) Get(ctx context.Context, request *GetRequest) (*GetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, request)
	ret0, _ := ret[0].(*GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRemoteStorageMockRecorder) Get(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRemoteStorage)(nil).Get), ctx, request)
}

// Put mocks base method.
func (m *MockRemoteStorage) Put(ctx context.Context, request *PutRequest) (*PutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, request)
	ret0, _ := ret[0].(*PutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockRemoteStorageMockRecorder) Put(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockRemoteStorage)(nil).Put), ctx, request)
}

// MockLocalStorage is a mock of LocalStorage interface.
type MockLocalStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLocalStorageMockRecorder
	isgomock struct{}
}

// MockLocalStorageMockRecorder is the mock recorder for MockLocalStorage.
type MockLocalStorageMockRecorder struct {
	mock *MockLocalStorage
}

// NewMockLocalStorage creates a new mock instance.
func NewMockLocalStorage(ctrl *gomock.Controller) *MockLocalStorage {
	mock := &MockLocalStorage{ctrl: ctrl}
	mock.recorder = &MockLocalStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalStorage) EXPECT() *MockLocalStorageMockRecorder {
	return m.recorder
}

// GetLocal mocks base method.
func (m *MockLocalStorage) GetLocal(ctx context.Context, request *LocalGetRequest) (*LocalGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocal", ctx, request)
	ret0, _ := ret[0].(*LocalGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocal indicates an expected call of GetLocal.
func (mr *MockLocalStorageMockRecorder) GetLocal(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocal", reflect.TypeOf((*MockLocalStorage)(nil).GetLocal), ctx, request)
}

// GetLocalObject mocks base method.
func (m *MockLocalStorage) GetLocalObject(ctx context.Context, request *LocalObjectGetRequest) (*LocalObjectGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalObject", ctx, request)
	ret0, _ := ret[0].(*LocalObjectGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLocalObject indicates an expected call of GetLocalObject.
func (mr *MockLocalStorageMockRecorder) GetLocalObject(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalObject", reflect.TypeOf((*MockLocalStorage)(nil).GetLocalObject), ctx, request)
}

// PutLocal mocks base method.
func (m *MockLocalStorage) PutLocal(ctx context.Context, request *LocalPutRequest) (*LocalPutResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutLocal", ctx, request)
	ret0, _ := ret[0].(*LocalPutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutLocal indicates an expected call of PutLocal.
func (mr *MockLocalStorageMockRecorder) PutLocal(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutLocal", reflect.TypeOf((*MockLocalStorage)(nil).PutLocal), ctx, request)
}

// MockCompressionCodec is a mock of CompressionCodec interface.
type MockCompressionCodec struct {
	ctrl     *gomock.Controller
	recorder *MockCompressionCodecMockRecorder
	isgomock struct{}
}

// MockCompressionCodecMockRecorder is the mock recorder for MockCompressionCodec.
type MockCompressionCodecMockRecorder struct {
	mock *MockCompressionCodec
}

// NewMockCompressionCodec creates a new mock instance.
func NewMockCompressionCodec(ctrl *gomock.Controller) *MockCompressionCodec {
	mock := &MockCompressionCodec{ctrl: ctrl}
	mock.recorder = &MockCompressionCodecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompressionCodec) EXPECT() *MockCompressionCodecMockRecorder {
	return m.recorder
}

// Compress mocks base method.
func (m *MockCompressionCodec) Compress(req *CompressRequest) (*CompressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compress", req)
	ret0, _ := ret[0].(*CompressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compress indicates an expected call of Compress.
func (mr *MockCompressionCodecMockRecorder) Compress(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compress", reflect.TypeOf((*MockCompressionCodec)(nil).Compress), req)
}

// Decompress mocks base method.
func (m *MockCompressionCodec) Decompress(req *DecompressRequest) (*DecompressResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decompress", req)
	ret0, _ := ret[0].(*DecompressResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decompress indicates an expected call of Decompress.
func (mr *MockCompressionCodecMockRecorder) Decompress(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decompress", reflect.TypeOf((*MockCompressionCodec)(nil).Decompress), req)
}
